name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          python3-pip \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          cmake \
          libffi-dev \
          libssl-dev \
          git \
          zip \
          unzip \
          openjdk-17-jdk

    - name: Install Python dependencies
      run: |
        pip install buildozer cython

    - name: Check and update buildozer.spec
      run: |
        # Проверяем, существует ли buildozer.spec
        if [ -f buildozer.spec ]; then
          echo "buildozer.spec already exists, updating requirements..."
          # Обновляем требования, если нужно
          if ! grep -q "requirements = python3,kivy,opencv,numpy,android" buildozer.spec; then
            echo "Updating requirements in buildozer.spec"
            sed -i 's/^requirements = .*/requirements = python3,kivy,opencv,numpy,android/' buildozer.spec
          fi
          # Обновляем разрешения, если нужно
          if ! grep -q "android.permissions = CAMERA,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE" buildozer.spec; then
            echo "Updating permissions in buildozer.spec"
            echo "android.permissions = CAMERA,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE" >> buildozer.spec
          fi
        else
          echo "Creating new buildozer.spec"
          buildozer init
          echo "requirements = python3,kivy,opencv,numpy,android" >> buildozer.spec
          echo "android.permissions = CAMERA,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE" >> buildozer.spec
        fi

    - name: Accept Android licenses
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        yes | /home/runner/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager --licenses

    - name: Install Android SDK components
      run: |
        /home/runner/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"

    - name: Build with Buildozer
      run: |
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: bin/*.apk
