name: Build Android APK (Simple)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        pip install --upgrade pip
        pip install buildozer cython

    - name: Create main.py if it doesn't exist
      run: |
        if [ ! -f main.py ]; then
          cat > main.py << 'EOF'
        from kivy.app import App
        from kivy.uix.label import Label

        class MotionDetectorApp(App):
            def build(self):
                return Label(text='Motion Detector App\nReady to detect motion!')

        if __name__ == '__main__':
            MotionDetectorApp().run()
        EOF
        fi

    - name: Create buildozer.spec
      run: |
        cat > buildozer.spec << 'EOF'
        [app]
        title = Motion Detector
        package.name = motiondetector
        package.domain = org.example
        source.dir = .
        version = 0.1
        requirements = python3,kivy
        
        [buildozer]
        log_level = 2
        
        [android]
        android.permissions = CAMERA,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE
        android.api = 30
        android.minapi = 21
        android.ndk = 25b
        android.accept_sdk_license = True
        android.gradle_dependencies = 
        android.auto_accept_sdk_license = True
        EOF

    - name: Accept Android licenses automatically
      run: |
        # Create a script to auto-accept licenses
        mkdir -p $HOME/.android
        echo "count=0" > $HOME/.android/repositories.cfg

    - name: Build APK
      run: |
        # Let buildozer handle everything automatically
        buildozer android debug
      env:
        ANDROID_ACCEPT_SDK_LICENSE: y

    - name: List files after build
      run: |
        echo "Contents of current directory:"
        ls -la
        echo "Contents of bin directory:"
        ls -la bin/ || echo "bin directory not found"
        echo "Searching for APK files:"
        find . -name "*.apk" -type f || echo "No APK files found"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: motion-detector-apk
        path: |
          bin/*.apk
          **/*.apk
      if: always()
