name: Build Android APK (Alternative with Android Setup)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

    - name: Create main.py
      run: |
        cat > main.py << 'EOF'
        from kivy.app import App
        from kivy.uix.label import Label

        class MotionDetectorApp(App):
            def build(self):
                return Label(text='Motion Detector App\nReady to detect motion!')

        if __name__ == '__main__':
            MotionDetectorApp().run()
        EOF

    - name: Initialize buildozer
      run: buildozer init

    - name: Update buildozer.spec
      run: |
        sed -i 's/title = My Application/title = Motion Detector/' buildozer.spec
        sed -i 's/package.name = myapp/package.name = motiondetector/' buildozer.spec
        sed -i 's/package.domain = org.test/package.domain = org.example/' buildozer.spec

    - name: Accept SDK licenses
      run: yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: motion-detector-apk
        path: bin/*.apk

